export type StackType =
  | 'MESSAGE_MEMBER_TO_CLINICIAN'
  | 'MESSAGE_CLINICIAN_TO_MEMBER'
  | 'MESSAGE_MEMBER_TO_MENTOR'
  | 'MESSAGE_MENTOR_TO_MEMBER'
  | 'MESSAGE_SYSTEM_TO_CLINICIAN'
  | 'MESSAGE_SYSTEM_TO_MEMBER'
  | 'MESSAGE_SYSTEM_TO_MENTOR';
