export enum ProfileType {
  MEMBER = 'MEMBER',
  CLINICIAN = 'CLINICIAN',
  MENTOR = 'MENTOR',
}
export enum ProfileRole {
  UNVERIFIED_CANDIDATE = 'UNVERIFIED_CANDIDATE',
  CANDIDATE = 'CANDIDATE',
  MEMBER = 'MEMBER',
  MENTOR_CANDIDATE = 'MENTOR_CANDIDATE',
  MENTOR = 'MENTOR',
  COACH = 'COACH',
  CLINICIAN = 'CLINICIAN',
  LEAD_CLINICIAN = 'LEAD_CLINICIAN',
  OPERATIONS = 'OPERATIONS',
  SUPERADMIN = 'SUPERADMIN',
  IMPERSONATOR = 'IMPERSONATOR',
  IMPERSONATABLE = 'IMPERSONATABLE',
}
