export enum Types {
  FETCH_EVENTS_BY_USER_ID = 'FETCH_EVENTS_BY_USER_ID',
  DELETE_EVENT_BY_ID = 'DELETE_EVENT_BY_ID',
  DELETE_EVENT_BY_ID_SUCCESS = 'DELETE_EVENT_BY_ID_SUCCESS',
  DELETE_EVENT_BY_ID_ERROR = 'DELETE_EVENT_BY_ID_ERROR',
  FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR',
  FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS',
}
