export enum Types {
  FETCH_PROFILE_FOR_ID = 'FETCH_PROFILE_FOR_ID',
  FETCH_PROFILE_FOR_IDP_ID = 'FETCH_PROFILE_FOR_IDP_ID',
  PROFILE_ERROR = 'PROFILE_ERROR',
  PROFILE_SUCCESS = 'PROFILE_SUCCESS',
}
