export enum Types {
  GET_QUESTIONSET_REQUEST = 'GET_QUESTIONSET_REQUEST',
  PATCH_QUESTIONSET_REQUEST = 'PATCH_QUESTIONSET_REQUEST',
  GET_QUESTIONSET_SUCCESS = 'GET_QUESTIONSET_SUCCESS',
  QUESTIONSET_ERROR = 'QUESTIONSET_ERROR',
  GET_QUESTIONSETS_SUCCESS = 'GET_QUESTIONSETS_SUCCESS',
  GRAB_QUESTIONSET = 'GRAB_QUESTIONSET',
  RESET_QUESTIONSET = 'RESET_QUESTIONSET',
}
