export enum Types {
  UPDATE_QUESTIONSET_INFORMATION = 'UPDATE_QUESTIONSET_INFORMATION',
  UPDATE_HINT_STATUS = 'UPDATE_HINT_STATUS',
  SUCCESS_HINT_UPDATED = 'SUCCESS_HINT_UPDATED',
  SUCCESS_SET_QUESTIONSET_INFORMATION = 'SUCCESS_SET_QUESTIONSET_INFORMATION',
}
