export enum Types {
  FETCH_STACK_REQUEST = 'FETCH_STACK_REQUEST',
  CREATE_DRAFT_STACK_REQUEST = 'CREATE_DRAFT_STACK_REQUEST',
  PUBLISH_DRAFT_STACK_REQUEST = 'PUBLISH_DRAFT_STACK_REQUEST',
  GET_STACK_SUCCESS = 'GET_STACK_SUCCESS',
  STACK_ERROR = 'STACK_ERROR',
  GET_STACKS_SUCCESS = 'GET_STACKS_SUCCESS',
}
